# **Jupyter Lab**の使い方

### Python 基本 「四則計算」　＋　ー　×　÷

In [13]:
a = 1

%： 余りを求める

In [10]:
a = '10%3 + 3'

In [11]:
print(a)

10%3 + 3


In [12]:
type(a)

str

### リスト：

In [13]:
c = [1,2,3]
c

[1, 2, 3]

In [14]:
type(c)

list

### 辞書： キーと値をペアする

In [15]:
d = {'Python':'3','Swift':'Xcode'}
d

{'Python': '3', 'Swift': 'Xcode'}

In [20]:
type(d)

dict

In [37]:
dict = {1:'Python',2:'Swift',3:'Dart'}
print(dict.get(0, 'Not Found'))

Not Found


In [33]:
dict[4] = 'C#'
dict

{1: 'Python', 2: 'Swift', 3: 'Dart', 4: 'C#'}

In [34]:
del dict[3]
dict

{1: 'Python', 2: 'Swift', 4: 'C#'}

In [36]:
dict.clear()
dict

{}

### キーや値を取り出す keys, values, items

In [41]:
for x in dict.items():
    print(x)

(1, 'Python')
(2, 'Swift')
(3, 'Dart')


In [42]:
data = [
    ['001','Hero','Mario','Mario.Bros'],
    ['002','Heroine','Sams','Metroid'],
    ['003','Kight','Link','Zelda']
]
data

[['001', 'Hero', 'Mario', 'Mario.Bros'],
 ['002', 'Heroine', 'Sams', 'Metroid'],
 ['003', 'Kight', 'Link', 'Zelda']]

In [49]:
member_information = {}
for record in data:
    key = record[0]
    info = record[1:]
    member_information[key] = info

In [44]:
for key,info in member_information.items():
    print(key, info)

001 ['Hero', 'Mario', 'Mario.Bros']
002 ['Heroine', 'Sams', 'Metroid']
003 ['Kight', 'Link', 'Zelda']


In [50]:
member_information

{'001': ['Hero', 'Mario', 'Mario.Bros'],
 '002': ['Heroine', 'Sams', 'Metroid'],
 '003': ['Kight', 'Link', 'Zelda']}

***

### **Pandas** のインポート

In [68]:
import pandas as pd

In [2]:
pd.Series([1,2,3])

0    1
1    2
2    3
dtype: int64

In [33]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]])
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [38]:
print(d)

{'Python': '3', 'Swift': 'Xcode'}


>引用されたテキスト

ソースコードの記述
```Python
def main():
    pass
```

In [45]:
df = pd.DataFrame([['名前','日付','スコア'],['太郎','12/1','90'],['一郎','6/1','50']])
df

0     1    2
0  名前    日付  スコア
1  太郎  12/1   90
2  一郎   6/1   50

一番上の見出しを別にするには

In [65]:
arr1 = ['Python'] * 5 + ['Swift'] * 5 + ['C#'] * 5
arr2 = ['データ','アプリ','グラフ','画像','自動化']*3
arr3 = [np.random.randint(0,100) for i in range(15)]
print(arr1,arr2,arr3)

['Python', 'Python', 'Python', 'Python', 'Python', 'Swift', 'Swift', 'Swift', 'Swift', 'Swift', 'C#', 'C#', 'C#', 'C#', 'C#'] ['データ', 'アプリ', 'グラフ', '画像', '自動化', 'データ', 'アプリ', 'グラフ', '画像', '自動化', 'データ', 'アプリ', 'グラフ', '画像', '自動化'] [52, 80, 20, 51, 89, 48, 83, 60, 78, 45, 79, 56, 46, 11, 77]


In [66]:
data = list(zip(arr1,arr2,arr3))
data

[('Python', 'データ', 52),
 ('Python', 'アプリ', 80),
 ('Python', 'グラフ', 20),
 ('Python', '画像', 51),
 ('Python', '自動化', 89),
 ('Swift', 'データ', 48),
 ('Swift', 'アプリ', 83),
 ('Swift', 'グラフ', 60),
 ('Swift', '画像', 78),
 ('Swift', '自動化', 45),
 ('C#', 'データ', 79),
 ('C#', 'アプリ', 56),
 ('C#', 'グラフ', 46),
 ('C#', '画像', 11),
 ('C#', '自動化', 77)]

In [85]:
df = pd.DataFrame(data=data, columns=['Language','category','Values'])
#df.info()
df[:5]
#print(df[:5])

Language category  Values
0   Python      データ      52
1   Python      アプリ      80
2   Python      グラフ      20
3   Python       画像      51
4   Python      自動化      89

In [87]:
df['Values'][:10]

0    52
1    80
2    20
3    51
4    89
5    48
6    83
7    60
8    78
9    45
Name: Values, dtype: int64

Zip関数

In [1]:
list1 = [1,2,3]
list2 = ['Apple', 'Orange', 'Kiwi']
dict(zip(list1,list2))

{1: 'Apple', 2: 'Orange', 3: 'Kiwi'}

### ファイルのアップロード　ひだりメニューの⬆︎から

In [19]:
df1 = pd.read_csv('covid19_y.csv')

In [20]:
df1.head()

No  全国地方自治体コード 都道府県名 市区町村名         公表日 患者_年代 患者_状態  患者_退院済フラグ
0   1      141003  神奈川県   横浜市  2020-02-18   60代    退院        1.0
1   2      141003  神奈川県   横浜市  2020-02-20   60代    退院        1.0
2   3      141003  神奈川県   横浜市  2020-02-21   30代    退院        1.0
3   4      141003  神奈川県   横浜市  2020-02-28   50代    退院        1.0
4   5      141003  神奈川県   横浜市  2020-03-03   20代    退院        1.0

In [21]:
df1.tail()

No  全国地方自治体コード 都道府県名 市区町村名         公表日 患者_年代 患者_状態  患者_退院済フラグ
5911  5930      141003  神奈川県   横浜市  2020-11-30   50代    軽症        NaN
5912  5931      141003  神奈川県   横浜市  2020-11-30   40代    軽症        NaN
5913  5932      141003  神奈川県   横浜市  2020-11-30   40代    軽症        NaN
5914  5933      141003  神奈川県   横浜市  2020-11-30   20代   無症状        NaN
5915  5934      141003  神奈川県   横浜市  2020-11-30   20代   無症状        NaN

In [22]:
df1[['No','公表日','患者_年代']].head()

No         公表日 患者_年代
0   1  2020-02-18   60代
1   2  2020-02-20   60代
2   3  2020-02-21   30代
3   4  2020-02-28   50代
4   5  2020-03-03   20代

In [ ]:
# うまくいかない例

In [24]:
# df.iloc[行,列]
df1.iloc[:,0:3].head()

No  全国地方自治体コード 都道府県名
0   1      141003  神奈川県
1   2      141003  神奈川県
2   3      141003  神奈川県
3   4      141003  神奈川県
4   5      141003  神奈川県

In [25]:
df2 = pd.read_csv('revized_covid19.csv')

In [30]:
df[df2['患者_年代']>50].head(10)

No  全国地方自治体コード 都道府県名 市区町村名         公表日  患者_年代 患者_状態  患者_退院済フラグ
0    1      141003  神奈川県   横浜市  2020/02/18   60.0    退院        1.0
1    2      141003  神奈川県   横浜市  2020/02/20   60.0    退院        1.0
5    6      141003  神奈川県   横浜市  2020/03/05   60.0    退院        1.0
6    7      141003  神奈川県   横浜市  2020/03/05   70.0    退院        1.0
7    8      141003  神奈川県   横浜市  2020/03/11   70.0    退院        1.0
9   10      141003  神奈川県   横浜市  2020/03/12   70.0    退院        1.0
10  11      141003  神奈川県   横浜市  2020/03/17   70.0    退院        1.0
11  12      141003  神奈川県   横浜市  2020/03/17   70.0    退院        1.0
12  13      141003  神奈川県   横浜市  2020/03/17   70.0    退院        1.0
14  15      141003  神奈川県   横浜市  2020/03/21   90.0    死亡        NaN

In [33]:
df.sort_values(by='患者_年代')

No  全国地方自治体コード 都道府県名 市区町村名         公表日  患者_年代 患者_状態  患者_退院済フラグ
43      44      141003  神奈川県   横浜市  2020/04/03    2.0    退院        1.0
44      45      141003  神奈川県   横浜市  2020/04/03    2.0    退院        1.0
2126  2129      141003  神奈川県   横浜市  2020/09/02    5.0    退院        1.0
2465  2468      141003  神奈川県   横浜市  2020/09/09    5.0    退院        1.0
2464  2467      141003  神奈川県   横浜市  2020/09/09    5.0    退院        1.0
...    ...         ...   ...   ...         ...    ...   ...        ...
748    749      141003  神奈川県   横浜市  2020/07/16    NaN    退院        1.0
749    750      141003  神奈川県   横浜市  2020/07/16    NaN    退院        1.0
795    796      141003  神奈川県   横浜市  2020/07/19    NaN    退院        1.0
892    893      141003  神奈川県   横浜市  2020/07/26    NaN    退院        1.0
4295  4308      141003  神奈川県   横浜市  2020/11/09    NaN    退院        1.0

[5916 rows x 8 columns]

### Numpy の基本

import numpy as np

In [35]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [36]:
x.shape

(3,)

In [37]:
x.ndim

1

In [38]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [40]:
y.ndim

2

In [42]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
y.mean()

5.0

リンクの表示１: https://developers.line.biz/ja/ 

リンクの表示２ [Link](https://developers.line.biz/ja/)

[Google][1]/[Line][2]

[1]: https://www.google.com/?hl=ja "Google"
[2]: https://developers.line.biz/ja/ "Line"

![Pythonで始める数学の冒険](124105053_365233551215927_6687424982830452009_n.jpg "Image")

<img src="124105053_365233551215927_6687424982830452009_n.jpg" width="100px">

1. k
2. l
1. l

$$
\int_a^b f(x) dx \\
\iiint_D dx \\
$$

In [3]:
import numpy as np

In [10]:
arr = np.array([10,20,30])
print(arr)

[10 20 30]


In [13]:
arr1 = np.arange(0,100,20)
arr2 = np.linspace(0,100,5)
print(arr1,arr2)

[ 0 20 40 60 80] [  0.  25.  50.  75. 100.]


In [52]:
print(arr)
print(arr + 10)
print(arr % 2)

[10 20 30]
[20 30 40]
[0 0 0]


## ListとNumpy array(ベクトル)の違い

In [53]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8]


In [54]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1 + arr2)

[ 6  8 10 12]


#### 単位行列の作成

In [56]:
arr3 = np.identity(3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [57]:
arr4 = np.eye(5,7,2)
arr4

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

ベクトルから行列への変換

In [58]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr1.reshape((3,3))
print(arr1)
print(arr2)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


行列からベクトルへ

In [5]:
arr1 = np.diag([1,2,3,5])
arr2 = np.ravel(arr1)
print(arr1)
print(arr2)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]
[1 0 0 0 0 2 0 0 0 0 3 0 0 0 0 5]


転置について

In [4]:
arr1 = np.array([1,2,3,5,8,13,21,34,55])
arr2 = arr1.reshape((3,3))
print(arr2)
print(arr2.T)

[[ 1  2  3]
 [ 5  8 13]
 [21 34 55]]
[[ 1  5 21]
 [ 2  8 34]
 [ 3 13 55]]


ベクトルの結合

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([5,8,13])
arr3 = arr1 + arr2
print(arr3)
arr4 = np.ravel([arr1,arr2])
print(arr4)

[ 6 10 16]
[ 1  2  3  5  8 13]
