In [3]:
quotes = {'Moe':'A wise guy, huh? ', 
    'Larry':'PPP', 
    'Curly':'Ow!'
    }
name = 'Curly'
print(name, 'says:', quotes[name])


Curly says: Ow!


In [13]:
poem = '''There was a Norway,
Who casually sat in doorway,
When I was in the sky.'''

In [14]:
print(poem)

There was a Norway,
Who casually sat in doorway,
When I was in the sky.


In [4]:
palindrome = 'A man,\nA plan, \nA canal:'
print(palindrome)

A man,
A plan, 
A canal:


スライス

In [6]:
letters = '123456789'
len(letters)

9

split() を使った分割

In [3]:
strings = 'yokohama_circular_economy_plus_school'
strings.split('_')

['yokohama', 'circular', 'economy', 'plus', 'school']

In [8]:
strings.endswith('ool')

True

In [11]:
word = 'circular'
strings.find(word)

9

replace(書き換えたい部分,書き換え後,回数)

In [23]:
setup = 'a duck goes into a bar...'


In [22]:
setup.replace('a', 'A', 3)

'A duck goes into A bAr...'

extend(  ) を使ってリストを結合させることができる

In [27]:
location = ['CN_museum','landmark_tower']
loc_plus = ['hammer_head','marina']
location.extend(loc_plus)

In [28]:
location

['CN_museum', 'landmark_tower', 'hammer_head', 'marina']

In [29]:
location.insert(1, 'World_Gate')
location

['CN_museum', 'World_Gate', 'landmark_tower', 'hammer_head', 'marina']

In [30]:
del location[2]
location

['CN_museum', 'World_Gate', 'hammer_head', 'marina']

In [33]:
'CN' in location

False

In [36]:
lists = ['meet','meet','vegetable','meet']
lists.count('meet')

3

In [37]:
friends = ['Harry', 'Hermione','Ron']
separator = ' * '
joined = separator.join(friends)
joined

'Harry * Hermione * Ron'

In [38]:
separated = joined.split(separator)
separated

['Harry', 'Hermione', 'Ron']

## sort( ) 要素の並べ替え

In [40]:
teams = ['real_madrid','manchester_u','manchester_c','lyon']
sorted_teams = sorted(teams)
sorted_teams

['lyon', 'manchester_c', 'manchester_u', 'real_madrid']

In [41]:
teams

['real_madrid', 'manchester_u', 'manchester_c', 'lyon']

In [42]:
teams.sort()
teams

['lyon', 'manchester_c', 'manchester_u', 'real_madrid']

## 3.2.19

In [53]:
a = [1,2,3]
a

[1, 2, 3]

In [54]:
b = a
b

[1, 2, 3]

In [55]:
b = a.copy()
b

[1, 2, 3]

In [56]:
a[0] = 'changed'
a

['changed', 2, 3]

In [57]:
b

[1, 2, 3]

## Tuple

In [62]:
empty_tuple = 'tuple',
empty_tuple

('tuple',)

タプルのアンパック

In [63]:
sample_tuple = (1,2,3)
a,b,c = sample_tuple

## Dictionary （key:value のペア）

In [67]:
players = {
    'Beckham': 7,
    'Neuer': 1,
    'Ronaldo': 7,
}
players

{'Beckham': 7, 'Neuer': 1, 'Ronaldo': 7}

In [68]:
players['Ronaldo'] = 3
players

{'Beckham': 7, 'Neuer': 1, 'Ronaldo': 3}

In [71]:
other_players = {'Hasebe': 17, 'Rooney': 10}
players.update(other_players)
players

{'Beckham': 7, 'Neuer': 1, 'Ronaldo': 3, 'Hasebe': 17, 'Rooney': 10}

In [74]:
players.get('Xavi', 'Not in players')

'Not in players'

In [3]:
signals = {'green':'go','yellow':'stay', 'red':'stop'}
list(signals.values())

['go', 'stay', 'stop']

In [4]:
list(signals.items())

[('green', 'go'), ('yellow', 'stay'), ('red', 'stop')]

## 集合

In [7]:
empty_set = set()
empty_set

set()

# Numpy

In [2]:
import numpy as np

In [7]:
data1 = [6,7.5,8,0,1]

ndarray の生成

In [8]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [11]:
data2 = [[1,2,3,4],[5,6,7,8,]]
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
float_arr = arr2.astype(np.float64)
float_arr.dtype

dtype('float64')

In [42]:
arr = np.array([3.4,5.6,2.1])

In [44]:
arr.astype(np.int32)

array([3, 5, 2], dtype=int32)

In [49]:
numeric_strings = np.array(['1.54','2.42','4'], dtype=np.string_)

In [50]:
numeric_strings.astype(float)

array([1.54, 2.42, 4.  ])

In [51]:
int_array = np.arange(10)

In [98]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
arr[:,2] = 0
arr

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

要素ごとに加減乗除が計算される

In [55]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [57]:
arr2 = np.array([[0,4,1],[7,2,12]])
arr2

array([[ 0,  4,  1],
       [ 7,  2, 12]])

In [74]:
arr[1][2]

6

In [60]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [66]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr_slice = arr[2:5] 
arr_slice

array([2, 3, 4])

In [68]:
arr_slice[1] = 123
arr

array([  0,   1,   2, 123,   4,   5,   6,   7,   8,   9])

In [69]:
arr_slice[:] = 0
arr

array([0, 1, 0, 0, 0, 5, 6, 7, 8, 9])

In [92]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [93]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
old_values = arr3d[1,0].copy()

In [95]:
arr3d[1,0] = 0
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [96]:
arr3d[1,0] = old_values

In [97]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [1]:
empty_set = set()
empty_set

set()

In [10]:
drinks = {
    'martini': {'vodka', 'vermouth'},
    'black russian': {'vodka', 'kahlua'},
    'manhattan': {'cream','vermouth','bitters'},
    'screwdriver':{'orange juice','vodka'}
}

In [25]:
mar = drinks['martini']
screwdriver = drinks['screwdriver']

In [27]:
mar.intersection(screwdriver)

{'vodka'}

In [28]:
mar | screwdriver

{'orange juice', 'vermouth', 'vodka'}

In [31]:
mar.union(screwdriver)

{'orange juice', 'vermouth', 'vodka'}

In [21]:
for name, contents in drinks.items():
    if contents & {'vermouth', 'orange juice'}:
        print(name)

martini
manhattan
screwdriver


In [20]:
cities= {'Big Apple':'NY','Madrid':'MRD','London':'LDN','Lyon':'LYN'}
for city ,short_name in cities.items():
    if 'Lyon' in city:
        print(short_name)

LYN


In [22]:
a = {1,2}
b = {2,3}

In [24]:
a.intersection(b)

{2}

In [32]:
a.difference(b)

{1}

In [39]:
disaster = True
if disaster:
    print('Woe!')
else:
    print('Boo!')

Woe!


In [42]:
count = 1
while count <= 5:
    print(count)
    count += 1

1
2
3
4
5


In [51]:
while True:
    stuff = input('Capitalize[type q to quit]: ')
    if stuff == "q":
        break
    print(stuff.capitalize())

In [53]:
while True:
    value = input('Integer,please [q to quit]:')
    if value == 'q':
        break
    number = int(value)
    if number % 2 == 0:
        continue
    print(number, 'squared is', number*number)

5 squared is 25


In [55]:
numbers = [1,2,5]
position = 0
while position < len(numbers):
    number = numbers[position]
    if number % 2 == 0:
        print('Found', number)
        break
    position += 1
else:
    print('No even number found')

Found 2


In [2]:
rabbits = ['Flopsy', 'Mopsy','Cottontail','Peter']
for rabbit in rabbits:
    print(rabbit)
    

Flopsy
Mopsy
Cottontail
Peter


In [9]:
accusation = {'room':'ballroom', 'weapon':'lead pipe', 'person':'Col. Mustard'}
# for card in accusation.keys():
#     print(card)
for card, content in accusation.items():
    print(card,':',content)

room : ballroom
weapon : lead pipe
person : Col. Mustard
