In [18]:
import pandas as pd
import numpy as np

In [4]:
a = pd.Series(['Python',3.8,2020],index=['language','Version','year'])
a

language    Python
Version        3.8
year          2020
dtype: object

In [11]:
df = pd.DataFrame(columns=['Language','Version','Year'],)
df

Empty DataFrame
Columns: [Language, Version, Year]
Index: []

In [14]:
df.loc[0] = ['Dart',2.3,2022]
df.loc[1] = ['Swift',5.1,2021]
df

Language  Version  Year
0     Dart      2.3  2022
1    Swift      5.1  2021

In [26]:
a_list = [['Dart',2.3,2022],['Swift',5.1,2021]]
a_list

df2 = pd.DataFrame(a_list, columns = ['Language','Version','Year'])
df2

Language  Version  Year
0     Dart      2.3  2022
1    Swift      5.1  2021

In [23]:
#creating DataFrame from array
a = np.arange(15).reshape(5,3)
print(a)

df3 = pd.DataFrame(a, columns = ['A','B','C'])
df3

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


A   B   C
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [27]:
np.transpose(df3)

0  1  2   3   4
A  0  3  6   9  12
B  1  4  7  10  13
C  2  5  8  11  14

In [28]:
#check the current directory
cwd = os.getcwd()
cwd

'/Users/jinsuzuki/Development/VS_Code/Learn_Python3/Pandas'

In [34]:
df = pd.read_csv('Users_data.csv')
df.shape

(24, 3)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   year    24 non-null     int64 
 1   month   24 non-null     object
 2   users   24 non-null     int64 
dtypes: int64(2), object(1)
memory usage: 704.0+ bytes


In [42]:
#filtering from DataFrame
df[df.users > 10]

year      month  users
9   2019    October     45
18  2020       July    300
20  2020  September     22
21  2020    October     33

In [43]:
df.groupby('year')['users'].sum()

year
2019     54
2020    380
Name: users, dtype: int64